---
author: "SPennington"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Diagnostics as of `r date()`

```{r, echo = FALSE, warning = FALSE, message = FALSE, results = 'hide'}
figures <- get(load("../outputs/figures.rda"))
```

```{r, echo = FALSE, message = FALSE}
# Auto-generate the sample size table
library(dplyr)
read.csv("../design/cores_collars.csv") %>% 
  group_by(Site, Experiment) %>% 
  summarise(N = n()) %>% 
  knitr::kable()
```

### CO2 flux over time

Color indicates origin/destination plot pairings. Panels: left to right - High, Medium, Low salinity; top to bottom - Low, Medium, and High elevation.

```{r, echo = FALSE}
figures$timeflux_plot_dest
```

### Composite temperature and flux data for all cores
```{r, echo = FALSE, warning = FALSE}
figures$q10_plot
```

### Soil moisture over time
```{r, echo = FALSE}
figures$timesm_plot
```

### CV distribution for each collar, n = number of measurements taken
```{r, echo = FALSE, warning = FALSE}
figures$ggCV_btwn_collars
```